services:
  product-service:
    image: ${ECR_REPOSITORY}/fc-product-service:1.0.0
    container_name: product-service
    ports:
      - "4084:4084"
    expose:
      - "4084"
    networks:
      - fcNet
      - jaegerNet
      - notificationsNet
    env_file:
      - ./.env
    environment:
      TZ: ${TIMEZONE}
      OTEL_SERVICE_NAME: "product-service"
      SPRING_PROFILES_ACTIVE: "docker"
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES}
      OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_EXPORTER_OTLP_PROTOCOL}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_METRIC_EXPORT_INTERVAL: ${OTEL_METRIC_EXPORT_INTERVAL}


networks:
  fcNet:
    name: fcNet
    external: true
    driver: bridge
  notificationsNet:
    name: notificationsNet
    external: true
    driver: bridge
  jaegerNet:
    name: jaegerNet
    external: true
    driver: bridge